apiVersion: v1
kind: Pod
metadata:
  name: hostpath-nginx
spec:
  terminationGracePeriodSeconds: 30
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html/      

  volumes:
  - name: www
    hostPath:
      path: /home/k8s/myFiles

  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: myData
          operator: In
          values:
          - present

      
